# SPDX-FileCopyrightText: Copyright 2022-2025 Arm Limited and/or its
# affiliates <open-source-office@arm.com>
# SPDX-License-Identifier: Apache-2.0
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

name: SDS-Examples AC6 build test
on:

  workflow_dispatch:
  #pull_request:
  #  branches: [main]
  #push:
  #  branches: [main]
  #schedule:
  #  - cron: '00 20 * * 6'


jobs:
  CI:
    strategy:
      matrix:
        context: [
          # toolchain,  example directory,                              artifact name,               project name, 
          { tool: AC6,  dir: ./Alif/AppKit-E7_USB,                      art_name: AppKit-E7_USB,     proj: SDS,    },
          { tool: AC6,  dir: ./Alif/AppKit-E8_USB,                      art_name: AppKit-E8_USB,     proj: SDS,    },
          { tool: AC6,  dir: ./Alif/DevKit-E8_ETH,                      art_name: DevKit-E8_ETH,     proj: SDS,    },
          { tool: AC6,  dir: ./Alif/DevKit-E8_USB,                      art_name: DevKit-E8_USB,     proj: SDS,    },
          { tool: AC6,  dir: ./ST/B-U585I-IOT02A/MotionRecognition,     art_name: MotionRecognition, proj: SDS,    },
          { tool: AC6,  dir: ./ST/B-U585I-IOT02A/KeywordSpotting,       art_name: KeywordSpotting,   proj: SDS,    },
          { tool: AC6,  dir: ./STM32N6570-DK/KeywordSpotting/FSBL,      art_name: KeywordSpotting,   proj: SDS,    },        
          { tool: AC6,  dir: ./STM32N6570-DK/KeywordSpotting/FSBL_LRUN, art_name: KeywordSpotting,   proj: SDS,    },
          { tool: AC6,  dir: ./STM32N6570-DK/KeywordSpotting/FSBL_XIP,  art_name: KeywordSpotting,   proj: SDS,    },
          ]

      fail-fast: false

    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v6

    - name: Activate vcpkg
      uses: ARM-software/cmsis-actions/vcpkg@v1
      with:
        config: ".ci/vcpkg-configuration.json"

    - name: Activate Arm tool license
      uses: ARM-software/cmsis-actions/armlm@v1

    - name: Cache downloaded packs
      uses: actions/cache@v5
      with:
        key: SDS
        path: /home/runner/.cache/arm/packs/.Download

    - name: ${{matrix.context.tool}} Build-Test for context ${{matrix.context.proj}}
      working-directory: ${{matrix.context.dir}}
      run: |
        cbuild ${{matrix.context.proj}}.csolution.yml --toolchain ${{matrix.context.tool}} --packs

    - name: Upload output for context ${{matrix.context.proj}}
      uses: actions/upload-artifact@v7
      with:
        name: ${{matrix.context.tool}}_build_${{matrix.context.art_name}}
        path: ${{matrix.context.dir}}/out

